name: sokia_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons:
  dio: ^4.0.0
  get:
  get_storage:
  splash_screen_view:
  flutter_launcher_icons:
  url_launcher:
  cached_network_image:
  google_fonts:
  google_maps_flutter:
  geolocator:
  material_floating_search_bar:
  expandable_group:
  rating_bar:
  lottie:
  pin_entry_field:
  flutter_countdown_timer:
  data_connection_checker:
  google_sign_in:
  firebase_messaging: ^9.0.1
  flutter_local_notifications: ^5.0.0
  firebase_core: ^1.0.2
  focused_menu:
  flutter_twitter_login: ^1.1.0
  firebase_auth: ^1.0.1
  flutter_facebook_login:
  apple_sign_in: ^0.1.0

  #  for chat
  animate_do: ^2.0.0
  emoji_picker: ^0.1.0
  shared_preferences:
  images_picker: ^1.0.0
  material_design_icons_flutter: ^4.0.5955
  bubble: ^1.2.1
  photo_view: ^0.11.1
  flutter_linkify:
    git:
      url: https://github.com/MohamedEL-Torky/flutter_linkify
  carousel_slider:
  flick_video_player: ^0.2.0
  fluttertoast: ^7.1.6
  share: ^0.6.5+3



dev_dependencies:
  flutter_test:
    sdk: flutter

  #native splash screens
  flutter_native_splash:

flutter_native_splash:
  #  color: "#0DA0B4"
  image: src/images/splash.png
  background_image: "src/images/splash_bg.png"
  android: true
  ios: true
  #  android_gravity: fill
  #  ios_content_mode: scaleAspectFill

  # run this command
  #  flutter pub run flutter_native_splash:create



flutter_icons:
  android: true
  ios: true
  image_path: "src/images/logo.png"


flutter:
  uses-material-design: true

  assets:
    - src/images/
    - src/json/
