name: sokia_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  animate_do: ^2.0.0
  bubble: ^1.2.1
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.3
  data_connection_checker: ^0.3.4
  dio: ^4.0.0
  emoji_picker:
  expandable_group: ^0.0.8
  fcm_config: ^3.1.1
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.2
  flick_video_player: ^0.2.0
  flutter:
    sdk: flutter
  flutter_countdown_timer: ^4.1.0
  flutter_launcher_icons: ^0.9.2
  flutter_linkify: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^1.2.4
  # flutter_facebook_login: ^3.0.0
  # flutter_twitter_login: ^1.1.0
  # sign_in_with_apple: ^3.2.0

  fluttertoast: ^7.1.6
  focused_menu: ^1.0.5
  geolocator: ^7.6.2
  get: ^4.3.8
  get_storage: ^2.0.3
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.0.10
  images_picker: ^1.2.4
  lottie: ^1.2.1
  material_design_icons_flutter: ^4.0.5955
  material_floating_search_bar: ^0.3.4
  photo_view: ^0.11.1
  pin_entry_field: ^0.0.4
  rating_bar: ^0.2.0
  share: ^0.6.5+3
  shared_preferences: ^2.0.8
  splash_screen_view: ^3.0.0
  url_launcher: ^6.0.12
  #Social login
  font_awesome_flutter: ^9.1.0
  flutter_login_facebook: ^1.1.0
  google_sign_in: ^5.1.1
  sign_in_with_apple: ^3.2.0
  twitter_login: ^4.0.1




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  #  color: "#0DA0B4"
  image: src/images/splash.png
  background_image: "src/images/splash_bg.png"
  android: true
  ios: true
  #  android_gravity: fill
  #  ios_content_mode: scaleAspectFill
  # run this command
  #  flutter pub run flutter_native_splash:create

flutter_icons:
  android: true
  ios: true
  image_path: "src/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - src/images/
    - src/json/
