name: sokia_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons:
  dio: ^3.0.10
  get:
  get_storage:
  splash_screen_view:
  flutter_launcher_icons:
  url_launcher:
  cached_network_image:
  google_fonts:
  google_maps_flutter:
  geolocator:
  material_floating_search_bar:
  expandable_group:
  rating_bar:
  lottie:
  pin_entry_field:
  flutter_countdown_timer:
  data_connection_checker:
  google_sign_in:
  toast:


dev_dependencies:
  flutter_test:
    sdk: flutter

#    native splash screens
  flutter_native_splash:

flutter_native_splash:
  color: "#FFFFFF"
  image: src/images/splash.png
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill

  # run this command
  #  flutter pub run flutter_native_splash:create



flutter_icons:
  android: true
  ios: true
  image_path: "src/images/logo.png"


flutter:
  uses-material-design: true

  assets:
    - src/images/
    - src/json/
